version: '3.8'
services:

  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '80:8000'
    depends_on:
      - redis
    
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass qwertyuiop
    volumes: 
      - redis:/data
volumes:
  redis:
    driver: local